import type { LabOrder } from "../types";

function escapeHtml(value: string): string {
  return String(value || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function resultRows(order: LabOrder): string {
  if (!order.results?.length) {
    return `<tr><td colspan="4" style="padding:8px">No quantitative results recorded.</td></tr>`;
  }
  return order.results
    .map(
      (row) => `<tr>
        <td style="padding:6px 8px;border-bottom:1px solid #e2e8f0">${escapeHtml(row.parameter)}</td>
        <td style="padding:6px 8px;border-bottom:1px solid #e2e8f0;font-weight:700;color:${row.isAbnormal ? "#b91c1c" : "#0f172a"}">${escapeHtml(row.value)} ${escapeHtml(row.unit)}</td>
        <td style="padding:6px 8px;border-bottom:1px solid #e2e8f0">${escapeHtml(row.referenceRange)}</td>
        <td style="padding:6px 8px;border-bottom:1px solid #e2e8f0">${row.isAbnormal ? "ABNORMAL" : "Normal"}</td>
      </tr>`
    )
    .join("");
}

export function labReportHtml(order: LabOrder): string {
  const critical = order.status === "CRITICAL" || order.flaggedCritical || order.priority === "Critical";
  return `<!DOCTYPE html><html><head><title>LankaLab ${escapeHtml(order.specimenId)}</title>
    <style>
      body{font-family:Georgia,serif;color:#0f172a;padding:28px;max-width:760px;margin:0 auto}
      h1{font-size:20px;margin:0;color:${critical ? "#991b1b" : "#065f46"}}
      .banner{padding:8px 12px;border-radius:8px;margin:12px 0;font-weight:700;font-size:13px}
      .crit{background:#fee2e2;color:#991b1b;border:1px solid #fecaca}
      .ok{background:#d1fae5;color:#065f46;border:1px solid #a7f3d0}
      table{width:100%;border-collapse:collapse;font-size:13px;margin-top:12px}
      th{text-align:left;background:#f8fafc;padding:6px 8px}
      .muted{color:#64748b;font-size:12px}
    </style></head><body>
    <h1>LankaLab Pathology Report</h1>
    <p class="muted">Colombo Central Patholab · Specimen ${escapeHtml(order.specimenId)} · ${escapeHtml(order.orderTime)}</p>
    <div class="banner ${critical ? "crit" : "ok"}">${critical ? "CRITICAL — notify the requesting clinic immediately" : "Completed assay"}</div>
    <p>Patient: <b>${escapeHtml(order.patientName)}</b> · ${order.age} yrs · ${escapeHtml(order.gender)}<br/>
    Test: <b>${escapeHtml(order.testType)}</b><br/>
    Clinic: <b>${escapeHtml(order.connectedClinic || "Not linked")}</b><br/>
    Unique Health ID: ${escapeHtml(order.suwasiriBarcode || "—")}<br/>
    Phone: ${escapeHtml(order.phone || "—")} · Email: ${escapeHtml(order.email || "—")}</p>
    ${order.notes ? `<p class="muted">Notes: ${escapeHtml(order.notes)}</p>` : ""}
    <table><thead><tr><th>Parameter</th><th>Result</th><th>Reference</th><th>Flag</th></tr></thead>
    <tbody>${resultRows(order)}</tbody></table>
    <p class="muted">Generated by LankaLab Portal. Not a substitute for clinician review.</p>
    </body></html>`;
}

export function reportSummaryText(order: LabOrder): string {
  const lines = (order.results || []).map((r) => `${r.parameter}: ${r.value} ${r.unit} (Ref ${r.referenceRange})`);
  return [
    `LankaLab report for ${order.patientName}`,
    `Test: ${order.testType}`,
    `Specimen: ${order.specimenId}`,
    `Clinic: ${order.connectedClinic || "—"}`,
    lines.join("\n") || "Results on file.",
    order.notes ? `Notes: ${order.notes}` : "",
  ]
    .filter(Boolean)
    .join("\n");
}

export function printLabReport(order: LabOrder) {
  const w = window.open("", "_blank", "noopener,noreferrer,width=860,height=720");
  if (!w) {
    alert("Allow pop-ups to print this report.");
    return;
  }
  w.document.write(labReportHtml(order));
  w.document.close();
  w.focus();
  w.print();
}

export function downloadLabReport(order: LabOrder) {
  const blob = new Blob([labReportHtml(order)], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `LankaLab-${order.specimenId || order.id}.html`;
  a.click();
  URL.revokeObjectURL(url);
}

export type ReferringDoctor = { name: string; email: string; clinic: string };

const FALLBACK_DOCTORS: ReferringDoctor[] = [
  { name: "Dr. Ambika Perera", clinic: "Kandy General Medical Clinic", email: "ambika@kgmc.lk" },
  { name: "Dr. Saubhik Bhaumik", clinic: "PrimeCare Medical Centre", email: "saubhik@primecare.lk" },
  { name: "Dr. SAUBHIK BHAUMIK", clinic: "PrimeCare Medical Centre - Colombo Central", email: "saubhik@primecare.lk" },
  { name: "Dr. Nalin Perera", clinic: "Colombo National Medical Clinic", email: "nalin@cnmc.lk" },
  { name: "Dr. Sunil Wickramasinghe", clinic: "Nawala Preventive Health Center", email: "sunil.w@nawala.lk" },
];

function loadManageDoctors(): ReferringDoctor[] {
  try {
    const raw = localStorage.getItem("lankalab-manage-v1");
    if (!raw) return [];
    const data = JSON.parse(raw) as { doctors?: { name?: string; email?: string; clinic?: string }[] };
    return (data.doctors || []).map((d) => ({
      name: d.name || "",
      email: d.email || "",
      clinic: d.clinic || "",
    }));
  } catch {
    return [];
  }
}

function norm(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
}

export function resolveReferringDoctor(order: LabOrder): ReferringDoctor | null {
  const key = (order.connectedClinic || "").trim();
  if (!key) return null;
  if (key.includes("@")) return { name: key, email: key, clinic: key };
  const needle = norm(key);
  const all = [...loadManageDoctors(), ...FALLBACK_DOCTORS];
  const hit = all.find((d) => {
    const name = norm(d.name);
    const clinic = norm(d.clinic);
    return needle === name || needle === clinic || needle.includes(name) || name.includes(needle) || needle.includes(clinic) || clinic.includes(needle);
  });
  return hit?.email ? hit : { name: key, email: "", clinic: key };
}

export function emailLabReport(order: LabOrder, opts?: { critical?: boolean; to?: string; doctor?: boolean }) {
  const doctor = opts?.doctor ? resolveReferringDoctor(order) : null;
  const to = (opts?.to || (opts?.doctor ? doctor?.email : order.email) || "").trim();
  if (!to) {
    alert(
      opts?.doctor
        ? `No email on file for the referring doctor (${order.connectedClinic || "not set"}). Add the doctor under Manage → Doctor access.`
        : `No email on file for ${order.patientName}. Add an email on the order first.`
    );
    return;
  }
  const critical = Boolean(opts?.critical || order.flaggedCritical || order.status === "CRITICAL");
  const who = opts?.doctor ? doctor?.name || "referring doctor" : order.patientName;
  const subject = `${critical ? "CRITICAL — " : ""}Lab report · ${order.testType} · ${order.patientName}`;
  const intro = opts?.doctor
    ? `Dear ${who},\n\nPlease find the LankaLab report for your patient ${order.patientName}.\n\n`
    : "";
  window.location.href = `mailto:${encodeURIComponent(to)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(intro + reportSummaryText(order))}`;
}

export function emailLabReportToDoctor(order: LabOrder, opts?: { email?: string; critical?: boolean }) {
  emailLabReport(order, { critical: opts?.critical, to: opts?.email, doctor: true });
}

export function textLabReport(order: LabOrder, opts?: { critical?: boolean }) {
  const raw = (order.phone || "").replace(/[^\d+]/g, "");
  if (!raw) {
    alert(`No mobile number on file for ${order.patientName}.`);
    return false;
  }
  const critical = Boolean(opts?.critical || order.flaggedCritical || order.status === "CRITICAL");
  const body = `${critical ? "CRITICAL: " : ""}${reportSummaryText(order)}`;
  const href = `sms:${raw}?body=${encodeURIComponent(body)}`;
  const link = document.createElement("a");
  link.href = href;
  link.style.display = "none";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  return true;
}

export function callPatient(order: LabOrder) {
  const raw = (order.phone || "").replace(/[^\d+]/g, "");
  if (!raw) {
    alert(`No phone number on file for ${order.patientName}.`);
    return;
  }
  window.location.href = `tel:${raw}`;
}
