import type { LabOrder } from "../types";

function escapeHtml(value: string): string {
  return String(value || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function resultRows(order: LabOrder): string {
  if (!order.results?.length) {
    return `<tr><td colspan="4" style="padding:8px">No quantitative results recorded.</td></tr>`;
  }
  return order.results
    .map(
      (row) => `<tr>
        <td style="padding:6px 8px;border-bottom:1px solid #e2e8f0">${escapeHtml(row.parameter)}</td>
        <td style="padding:6px 8px;border-bottom:1px solid #e2e8f0;font-weight:700;color:${row.isAbnormal ? "#b91c1c" : "#0f172a"}">${escapeHtml(row.value)} ${escapeHtml(row.unit)}</td>
        <td style="padding:6px 8px;border-bottom:1px solid #e2e8f0">${escapeHtml(row.referenceRange)}</td>
        <td style="padding:6px 8px;border-bottom:1px solid #e2e8f0">${row.isAbnormal ? "ABNORMAL" : "Normal"}</td>
      </tr>`
    )
    .join("");
}

export function labReportHtml(order: LabOrder): string {
  const critical = order.status === "CRITICAL" || order.flaggedCritical || order.priority === "Critical";
  return `<!DOCTYPE html><html><head><title>LankaLab ${escapeHtml(order.specimenId)}</title>
    <style>
      body{font-family:Georgia,serif;color:#0f172a;padding:28px;max-width:760px;margin:0 auto}
      h1{font-size:20px;margin:0;color:${critical ? "#991b1b" : "#065f46"}}
      .banner{padding:8px 12px;border-radius:8px;margin:12px 0;font-weight:700;font-size:13px}
      .crit{background:#fee2e2;color:#991b1b;border:1px solid #fecaca}
      .ok{background:#d1fae5;color:#065f46;border:1px solid #a7f3d0}
      table{width:100%;border-collapse:collapse;font-size:13px;margin-top:12px}
      th{text-align:left;background:#f8fafc;padding:6px 8px}
      .muted{color:#64748b;font-size:12px}
    </style></head><body>
    <h1>LankaLab Pathology Report</h1>
    <p class="muted">Colombo Central Patholab · Specimen ${escapeHtml(order.specimenId)} · ${escapeHtml(order.orderTime)}</p>
    <div class="banner ${critical ? "crit" : "ok"}">${critical ? "CRITICAL — notify the requesting clinic immediately" : "Completed assay"}</div>
    <p>Patient: <b>${escapeHtml(order.patientName)}</b> · ${order.age} yrs · ${escapeHtml(order.gender)}<br/>
    Test: <b>${escapeHtml(order.testType)}</b><br/>
    Clinic: <b>${escapeHtml(order.connectedClinic || "Not linked")}</b><br/>
    Unique Health ID: ${escapeHtml(order.suwasiriBarcode || "—")}<br/>
    Phone: ${escapeHtml(order.phone || "—")} · Email: ${escapeHtml(order.email || "—")}</p>
    ${order.notes ? `<p class="muted">Notes: ${escapeHtml(order.notes)}</p>` : ""}
    <table><thead><tr><th>Parameter</th><th>Result</th><th>Reference</th><th>Flag</th></tr></thead>
    <tbody>${resultRows(order)}</tbody></table>
    <p class="muted">Generated by LankaLab Portal. Not a substitute for clinician review.</p>
    </body></html>`;
}

export function reportSummaryText(order: LabOrder): string {
  const lines = (order.results || []).map((r) => `${r.parameter}: ${r.value} ${r.unit} (Ref ${r.referenceRange})`);
  return [
    `LankaLab report for ${order.patientName}`,
    `Test: ${order.testType}`,
    `Specimen: ${order.specimenId}`,
    `Clinic: ${order.connectedClinic || "—"}`,
    lines.join("\n") || "Results on file.",
    order.notes ? `Notes: ${order.notes}` : "",
  ]
    .filter(Boolean)
    .join("\n");
}

export function printLabReport(order: LabOrder) {
  const w = window.open("", "_blank", "noopener,noreferrer,width=860,height=720");
  if (!w) {
    alert("Allow pop-ups to print this report.");
    return;
  }
  w.document.write(labReportHtml(order));
  w.document.close();
  w.focus();
  w.print();
}

export function downloadLabReport(order: LabOrder) {
  const blob = new Blob([labReportHtml(order)], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `LankaLab-${order.specimenId || order.id}.html`;
  a.click();
  URL.revokeObjectURL(url);
}

export function emailLabReport(order: LabOrder, opts?: { critical?: boolean }) {
  const to = (order.email || "").trim();
  if (!to) {
    alert(`No email on file for ${order.patientName}. Add an email on the order first.`);
    return;
  }
  const critical = Boolean(opts?.critical || order.flaggedCritical || order.status === "CRITICAL");
  const subject = `${critical ? "CRITICAL — " : ""}${order.testType} · ${order.patientName}`;
  window.location.href = `mailto:${encodeURIComponent(to)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(reportSummaryText(order))}`;
}

export function textLabReport(order: LabOrder, opts?: { critical?: boolean }) {
  const raw = (order.phone || "").replace(/[^\d+]/g, "");
  if (!raw) {
    alert(`No mobile number on file for ${order.patientName}.`);
    return false;
  }
  const critical = Boolean(opts?.critical || order.flaggedCritical || order.status === "CRITICAL");
  const body = `${critical ? "CRITICAL: " : ""}${reportSummaryText(order)}`;
  const href = `sms:${raw}?body=${encodeURIComponent(body)}`;
  const link = document.createElement("a");
  link.href = href;
  link.style.display = "none";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  return true;
}

export function callPatient(order: LabOrder) {
  const raw = (order.phone || "").replace(/[^\d+]/g, "");
  if (!raw) {
    alert(`No phone number on file for ${order.patientName}.`);
    return;
  }
  window.location.href = `tel:${raw}`;
}
