import 'dart:io';
import 'dart:typed_data';

import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:url_launcher/url_launcher.dart';

import '../catalogs/patient_health_samples.dart';
import '../models/user_profile.dart';
import '../models/vault_report.dart';

/// Builds printable e-prescription PDFs and opens email / share flows.
abstract final class PrescriptionExportService {
  static Future<Uint8List> buildPdfBytes({
    required List<Prescription> medicines,
    required String clinicName,
    required String doctorName,
    UserProfile? patient,
  }) async {
    final doc = pw.Document();
    final issued = medicines.isNotEmpty
        ? (medicines.first.issuedAt ?? DateTime.now())
        : DateTime.now();
    final dateStr = DateFormat('dd/MM/yyyy').format(issued);
    final patientName =
        (patient?.name.isNotEmpty == true) ? patient!.name : 'Patient';
    final healthId = patient?.ceylonHealthId?.isNotEmpty == true
        ? patient!.ceylonHealthId!
        : (patient?.nic ?? '—');
    final region = patient?.region ?? 'Sri Lanka';
    final script = medicines.isNotEmpty ? medicines.first.code : 'EP-SAMPLE';

    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'SUWASIRI E-PRESCRIPTION',
                style: pw.TextStyle(
                  fontSize: 16,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 4),
              pw.Text('Pharmacist / MediLanka pharmacy copy'),
              pw.Divider(),
              pw.Text(doctorName,
                  style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
              pw.Text(clinicName),
              if (medicines.isNotEmpty)
                pw.Text(
                  'Prescriber No. ${medicines.first.prescriberNumber}',
                ),
              pw.SizedBox(height: 8),
              pw.Text("Patient's name: $patientName"),
              pw.Text('Ceylon Health ID / NIC: $healthId'),
              pw.Text('Address: $region, Sri Lanka'),
              pw.Text('Date: $dateStr'),
              pw.Text('Script No: $script'),
              pw.SizedBox(height: 16),
              pw.Text(
                'Medicines',
                style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              ),
              pw.SizedBox(height: 8),
              ...medicines.map(
                (m) => pw.Padding(
                  padding: const pw.EdgeInsets.only(bottom: 10),
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        m.medicine,
                        style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                      ),
                      if (m.schedule.isNotEmpty) pw.Text(m.schedule),
                      pw.Text(
                        'Dose: ${m.doseBadge.isEmpty ? m.code : m.doseBadge}',
                      ),
                    ],
                  ),
                ),
              ),
              pw.Spacer(),
              pw.Text('Doctor signature: ______________________'),
              pw.SizedBox(height: 8),
              pw.Text(
                'Generated by Suwasiri for Sri Lankan pharmacy / MediLanka portal use.',
                style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
              ),
            ],
          );
        },
      ),
    );

    return doc.save();
  }

  static Future<String> savePdfToDevice(Uint8List bytes, String filename) async {
    Directory? dir;
    try {
      dir = await getDownloadsDirectory();
    } catch (_) {}
    dir ??= await getApplicationDocumentsDirectory();
    final folder = Directory('${dir.path}/Suwasiri');
    if (!await folder.exists()) {
      await folder.create(recursive: true);
    }
    final file = File('${folder.path}/$filename');
    await file.writeAsBytes(bytes, flush: true);
    return file.path;
  }

  static Future<String> downloadPdf({
    required List<Prescription> medicines,
    required String clinicName,
    required String doctorName,
    UserProfile? patient,
  }) async {
    final bytes = await buildPdfBytes(
      medicines: medicines,
      clinicName: clinicName,
      doctorName: doctorName,
      patient: patient,
    );
    final name =
        'suwasiri_rx_${DateFormat('yyyyMMdd_HHmm').format(DateTime.now())}.pdf';
    try {
      return await savePdfToDevice(bytes, name);
    } catch (_) {
      await Printing.sharePdf(bytes: bytes, filename: name);
      return name;
    }
  }

  static Future<Uint8List> buildLabReportPdfBytes({
    required VaultReport report,
    UserProfile? patient,
  }) async {
    final doc = pw.Document();
    final dateStr = DateFormat('dd/MM/yyyy').format(report.date);
    final patientName =
        (patient?.name.isNotEmpty == true) ? patient!.name : 'Patient';
    final healthId = patient?.barcodeNumber ??
        patient?.ceylonHealthId ??
        patient?.nic ??
        '—';

    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'SUWASIRI LAB REPORT',
                style: pw.TextStyle(
                  fontSize: 16,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 4),
              pw.Text(report.facility ?? report.issuedBy),
              pw.Divider(),
              pw.Text('Patient: $patientName'),
              pw.Text('Health ID: $healthId'),
              pw.Text('Report: ${report.title}'),
              pw.Text('Date: $dateStr'),
              if (report.requestedBy != null)
                pw.Text('Requested by: ${report.requestedBy}'),
              pw.SizedBox(height: 16),
              pw.Text(
                'Results',
                style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              ),
              pw.SizedBox(height: 8),
              ...report.metrics.map(
                (m) => pw.Padding(
                  padding: const pw.EdgeInsets.only(bottom: 8),
                  child: pw.Row(
                    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                    children: [
                      pw.Expanded(
                        child: pw.Column(
                          crossAxisAlignment: pw.CrossAxisAlignment.start,
                          children: [
                            pw.Text(m.name),
                            if (m.normalRange.isNotEmpty)
                              pw.Text(
                                'Normal: ${m.normalRange}',
                                style: const pw.TextStyle(
                                  fontSize: 9,
                                  color: PdfColors.grey700,
                                ),
                              ),
                          ],
                        ),
                      ),
                      pw.Text('${m.value}  (${m.status})'),
                    ],
                  ),
                ),
              ),
              if (report.clinicalComments.isNotEmpty) ...[
                pw.SizedBox(height: 16),
                pw.Text(
                  'Laboratory Clinical Comments',
                  style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                ),
                pw.SizedBox(height: 6),
                pw.Text(report.clinicalComments),
              ],
              pw.Spacer(),
              pw.Text(
                'Generated by Suwasiri Vault for patient records.',
                style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
              ),
            ],
          );
        },
      ),
    );
    return doc.save();
  }

  static Future<void> downloadLabReportPdf({
    required VaultReport report,
    UserProfile? patient,
  }) async {
    final bytes = await buildLabReportPdfBytes(report: report, patient: patient);
    final name =
        'suwasiri_lab_${DateFormat('yyyyMMdd_HHmm').format(DateTime.now())}.pdf';
    await Printing.sharePdf(bytes: bytes, filename: name);
  }

  static Future<void> emailPrescription({
    required List<Prescription> medicines,
    required String clinicName,
    required String doctorName,
    required String toEmail,
    UserProfile? patient,
  }) async {
    final issued = medicines.isNotEmpty
        ? (medicines.first.issuedAt ?? DateTime.now())
        : DateTime.now();
    final dateStr = DateFormat('d MMM yyyy').format(issued);
    final patientName =
        (patient?.name.isNotEmpty == true) ? patient!.name : 'Patient';
    final script = prescriptionScriptNumber(medicines);
    final prescriber = medicines.isNotEmpty
        ? medicines.first.prescriberNumber
        : '1234567';
    final lines = medicines
        .map(
          (m) =>
              '• ${m.medicine} — ${m.schedule.isEmpty ? m.doseBadge : m.schedule}',
        )
        .join('\n');
    final subject = 'Suwasiri e-prescription — $clinicName';
    final body = '''
Suwasiri e-prescription (PDF attached)
Clinic: $clinicName
Doctor: $doctorName
Prescriber No.: $prescriber
Script No.: $script
Patient: $patientName
Issued: $dateStr

$lines
''';
    final bytes = await buildPdfBytes(
      medicines: medicines,
      clinicName: clinicName,
      doctorName: doctorName,
      patient: patient,
    );
    final name =
        'suwasiri_rx_${DateFormat('yyyyMMdd_HHmm').format(DateTime.now())}.pdf';
    try {
      await savePdfToDevice(bytes, name);
    } catch (_) {}

    final shared = await Printing.sharePdf(
      bytes: bytes,
      filename: name,
      subject: subject,
      body: body,
      emails: [toEmail],
    );
    if (shared) return;

    final uri = Uri.parse(
      'mailto:$toEmail'
      '?subject=${Uri.encodeComponent(subject)}'
      '&body=${Uri.encodeComponent(body)}',
    );
    if (await canLaunchUrl(uri)) {
      await launchUrl(uri, mode: LaunchMode.externalApplication);
    } else {
      throw Exception('Cannot open email app');
    }
  }

  static Future<Uint8List> buildCertificatePdfBytes({
    required DoctorCertificate certificate,
    UserProfile? patient,
  }) async {
    final doc = pw.Document();
    final dateStr = DateFormat('dd/MM/yyyy').format(certificate.date);
    final patientName =
        (patient?.name.isNotEmpty == true) ? patient!.name : 'Patient';
    final healthId = patient?.barcodeNumber ??
        patient?.ceylonHealthId ??
        patient?.nic ??
        '—';

    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'SUWASIRI DOCTOR CERTIFICATE',
                style: pw.TextStyle(
                  fontSize: 16,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 4),
              pw.Text(certificate.clinicName),
              pw.Divider(),
              pw.Text(certificate.title,
                  style: pw.TextStyle(
                    fontSize: 14,
                    fontWeight: pw.FontWeight.bold,
                  )),
              pw.SizedBox(height: 8),
              pw.Text('Certificate No: ${certificate.certificateNo}'),
              pw.Text('Date: $dateStr'),
              pw.Text('Doctor: ${certificate.doctor}'),
              pw.Text('Patient: $patientName'),
              pw.Text('Health ID: $healthId'),
              pw.SizedBox(height: 16),
              pw.Text(certificate.body),
              pw.Spacer(),
              pw.Text('Doctor signature: ______________________'),
              pw.SizedBox(height: 8),
              pw.Text(
                'Generated by Suwasiri Vault for patient records.',
                style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
              ),
            ],
          );
        },
      ),
    );
    return doc.save();
  }

  static Future<void> downloadCertificatePdf({
    required DoctorCertificate certificate,
    UserProfile? patient,
  }) async {
    final bytes = await buildCertificatePdfBytes(
      certificate: certificate,
      patient: patient,
    );
    final name =
        'suwasiri_cert_${DateFormat('yyyyMMdd_HHmm').format(DateTime.now())}.pdf';
    await Printing.sharePdf(bytes: bytes, filename: name);
  }

  static Future<void> emailCertificate({
    required DoctorCertificate certificate,
    required String toEmail,
    UserProfile? patient,
  }) async {
    final dateStr = DateFormat('d MMM yyyy').format(certificate.date);
    final patientName =
        (patient?.name.isNotEmpty == true) ? patient!.name : 'Patient';
    final subject = 'Suwasiri doctor certificate — ${certificate.title}';
    final body = '''
Suwasiri doctor certificate (PDF attached)
Title: ${certificate.title}
Certificate No.: ${certificate.certificateNo}
Doctor: ${certificate.doctor}
Clinic: ${certificate.clinicName}
Patient: $patientName
Issued: $dateStr

${certificate.body}
''';
    final bytes = await buildCertificatePdfBytes(
      certificate: certificate,
      patient: patient,
    );
    final name =
        'suwasiri_cert_${DateFormat('yyyyMMdd_HHmm').format(DateTime.now())}.pdf';
    try {
      await savePdfToDevice(bytes, name);
    } catch (_) {}

    final shared = await Printing.sharePdf(
      bytes: bytes,
      filename: name,
      subject: subject,
      body: body,
      emails: [toEmail],
    );
    if (shared) return;

    final uri = Uri.parse(
      'mailto:$toEmail'
      '?subject=${Uri.encodeComponent(subject)}'
      '&body=${Uri.encodeComponent(body)}',
    );
    if (await canLaunchUrl(uri)) {
      await launchUrl(uri, mode: LaunchMode.externalApplication);
    } else {
      throw Exception('Cannot open email app');
    }
  }
}
