import type { FeeScheduleItem, SuwasiriFeeService } from "../types";

export const FEE_CATEGORIES: FeeScheduleItem["category"][] = [
  "Standard Consult",
  "Long Consult",
  "Telehealth",
  "Care Plan",
  "Mental Health",
  "Procedure",
  "After Hours",
];

export const SUWASIRI_FEE_SERVICES: { value: SuwasiriFeeService; label: string }[] = [
  { value: "", label: "Not a Suwasiri special fee" },
  { value: "standard", label: "Suwasiri: Standard consultation" },
  { value: "medical_certificate", label: "Suwasiri: Medical certificate" },
  { value: "repeat_prescription", label: "Suwasiri: Repeat prescription" },
  { value: "review_results", label: "Suwasiri: Review results" },
];

export const DEFAULT_FEE_SCHEDULE: FeeScheduleItem[] = [
  {
    id: "fee-1",
    mbsItemNumber: "SL-OPD-01",
    description: "Standard OPD General Practice Consultation (< 15 mins)",
    category: "Standard Consult",
    mbsScheduleFee: 1500.0,
    mbsBenefit: 500.0,
    privateFee: 2000.0,
    gapFee: 1500.0,
    bulkBillable: false,
  },
  {
    id: "fee-2",
    mbsItemNumber: "SL-OPD-02",
    description: "Extended Chronic Disease Review (Diabetes / Hypertension 20-30 min)",
    category: "Long Consult",
    mbsScheduleFee: 2500.0,
    mbsBenefit: 800.0,
    privateFee: 3500.0,
    gapFee: 2700.0,
    bulkBillable: false,
  },
  {
    id: "fee-3",
    mbsItemNumber: "SL-NCD-03",
    description: "MoH PEN Protocol Comprehensive NCD Risk Assessment & Care Plan",
    category: "Care Plan",
    mbsScheduleFee: 3000.0,
    mbsBenefit: 3000.0,
    privateFee: 3000.0,
    gapFee: 0.0,
    bulkBillable: false,
  },
  {
    id: "fee-4",
    mbsItemNumber: "SL-HOME-04",
    description: "Domiciliary / Home Visit Doctor Consultation",
    category: "Care Plan",
    mbsScheduleFee: 4500.0,
    mbsBenefit: 1000.0,
    privateFee: 5500.0,
    gapFee: 4500.0,
    bulkBillable: false,
  },
  {
    id: "fee-5",
    mbsItemNumber: "SL-PROC-05",
    description: "Minor Surgical Procedure / Wound Suturing / Nebulisation",
    category: "Procedure",
    mbsScheduleFee: 2200.0,
    mbsBenefit: 500.0,
    privateFee: 3000.0,
    gapFee: 2500.0,
    bulkBillable: false,
  },
  {
    id: "fee-6",
    mbsItemNumber: "SL-TELE-06",
    description: "Suwasiri Telehealth Video Consultation (< 20 min)",
    category: "Telehealth",
    mbsScheduleFee: 1800.0,
    mbsBenefit: 600.0,
    privateFee: 2400.0,
    gapFee: 1800.0,
    bulkBillable: false,
  },
  {
    id: "fee-mc",
    mbsItemNumber: "SL-MC-01",
    description: "Medical Certificate (sick leave / fitness)",
    category: "Procedure",
    mbsScheduleFee: 1000.0,
    mbsBenefit: 0.0,
    privateFee: 1000.0,
    gapFee: 1000.0,
    bulkBillable: false,
    suwasiriService: "medical_certificate",
  },
  {
    id: "fee-rx",
    mbsItemNumber: "SL-RX-01",
    description: "Repeat Prescription (no full consult)",
    category: "Standard Consult",
    mbsScheduleFee: 800.0,
    mbsBenefit: 0.0,
    privateFee: 800.0,
    gapFee: 800.0,
    bulkBillable: false,
    suwasiriService: "repeat_prescription",
  },
  {
    id: "fee-rr",
    mbsItemNumber: "SL-RR-01",
    description: "Review Results / investigation follow-up",
    category: "Standard Consult",
    mbsScheduleFee: 1200.0,
    mbsBenefit: 0.0,
    privateFee: 1200.0,
    gapFee: 1200.0,
    bulkBillable: false,
    suwasiriService: "review_results",
  },
];
